#!/usr/bin/env python3
"""Regenerate README.md from esp32-s3-display-hq-test.yaml."""

from __future__ import annotations

from pathlib import Path
import sys

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Missing dependency: pyyaml") from exc


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "esp32-s3-display-hq-test.yaml"
README_PATH = ROOT / "README.md"


def _mapping(value: object) -> dict:
    return value if isinstance(value, dict) else {}


def _first_mapping(value: object) -> dict:
    if isinstance(value, list) and value:
        return _mapping(value[0])
    return _mapping(value)


def load_config() -> tuple[dict, str]:
    yaml_text = CONFIG_PATH.read_text(encoding="utf-8")
    data = yaml.safe_load(yaml_text)
    if not isinstance(data, dict):
        raise SystemExit(f"Invalid YAML structure in {CONFIG_PATH.name}")
    return data, yaml_text.rstrip() + "\n"


def render_readme(config: dict, yaml_text: str) -> str:
    esphome_cfg = _mapping(config.get("esphome"))
    esp32_cfg = _mapping(config.get("esp32"))
    framework_cfg = _mapping(esp32_cfg.get("framework"))
    psram_cfg = _mapping(config.get("psram"))
    spi_cfg = _first_mapping(config.get("spi"))
    display_cfg = _first_mapping(config.get("display"))

    device_name = esphome_cfg.get("name", "unknown")
    friendly_name = esphome_cfg.get("friendly_name", "unknown")
    board = esp32_cfg.get("board", "unknown")
    flash_size = esp32_cfg.get("flash_size", "unknown")
    framework = str(framework_cfg.get("type", "unknown")).upper()

    psram_mode = psram_cfg.get("mode", "unspecified")
    psram_speed = psram_cfg.get("speed", "unspecified")

    width = display_cfg.get("width", "?")
    height = display_cfg.get("height", "?")
    rotation = display_cfg.get("rotation", "unknown")
    update_interval = display_cfg.get("update_interval", "unknown")
    eight_bit = display_cfg.get("eightbitcolor", True)
    color_mode = "16-bit" if eight_bit is False else "8-bit"

    clk_pin = spi_cfg.get("clk_pin", "unknown")
    mosi_pin = spi_cfg.get("mosi_pin", "unknown")
    cs_pin = display_cfg.get("cs_pin", "unknown")
    dc_pin = display_cfg.get("dc_pin", "unknown")
    reset_pin = display_cfg.get("reset_pin", "unknown")

    return (
        "# ESP32-S3 Display Quality Test\n\n"
        "> This README is auto-generated from `esp32-s3-display-hq-test.yaml`.\n"
        "> Do not edit this file manually; run `python3 scripts/update_readme.py`.\n\n"
        "## Purpose\n\n"
        "- Test only high-quality display rendering on ESP32-S3\n"
        "- No sensors, no incubator logic, no extra components\n"
        "- Full-screen animation to stress drawing throughput and color quality\n\n"
        "## Device Summary\n\n"
        f"- Device name: `{device_name}`\n"
        f"- Friendly name: `{friendly_name}`\n"
        f"- Board: `{board}`\n"
        f"- Flash size: `{flash_size}`\n"
        f"- Framework: `{framework}`\n"
        f"- PSRAM: `{psram_mode}` @ `{psram_speed}`\n\n"
        "## Display Settings\n\n"
        f"- Resolution: `{width}x{height}`\n"
        f"- Rotation: `{rotation}`\n"
        f"- Color mode: `{color_mode}` (`eightbitcolor: {str(eight_bit).lower()}`)\n"
        f"- Update interval: `{update_interval}`\n\n"
        "## Pin Mapping\n\n"
        f"- `SPI CLK`  -> `{clk_pin}`\n"
        f"- `SPI MOSI` -> `{mosi_pin}`\n"
        f"- `TFT CS`   -> `{cs_pin}`\n"
        f"- `TFT DC`   -> `{dc_pin}`\n"
        f"- `TFT RST`  -> `{reset_pin}`\n\n"
        "## Validate / Compile\n\n"
        "```bash\n"
        "esphome config esp32-s3-display-hq-test.yaml\n"
        "esphome compile esp32-s3-display-hq-test.yaml\n"
        "```\n\n"
        "## Flash\n\n"
        "```bash\n"
        "esphome run esp32-s3-display-hq-test.yaml\n"
        "```\n\n"
        "## Full YAML\n\n"
        "```yaml\n"
        f"{yaml_text}"
        "```\n"
    )


def main() -> int:
    config, yaml_text = load_config()
    content = render_readme(config, yaml_text)
    old_content = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else ""

    if content == old_content:
        print("README.md is already up to date.")
        return 0

    README_PATH.write_text(content, encoding="utf-8")
    print("Updated README.md from esp32-s3-display-hq-test.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
